---
- name: update-console-setup
  command: setupcon --save

- name: reload-systemd
  systemd:
    daemon_reload: true

- name: restart-timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
